

server:
  port: 8001



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nagabhushanamn/micro-in-GL
          clone-on-start: true
          search-paths:
          - 'config-repo'
 
 
                    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'